In [1]:
!pip install gensim

In [2]:
import gensim
from gensim.models import Word2Vec, KeyedVectors

In [3]:
import gensim.downloader as api
wv= api.load('word2vec-google-news-300')

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [5]:
import pandas as pd

messages = pd.read_csv(
    '/content/drive/MyDrive/Colab/NLP-ML/spam.csv',
    names=['label', 'message'],
    encoding='latin-1',
    usecols=[0, 1]
)

In [6]:
messages

,label,message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."
...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...
5568,ham,Will �_ b going to esplanade fr home?
5569,ham,"Pity, * was in mood for that. So...any other s..."
5570,ham,The guy did some bitching but I acted like i'd...


In [7]:
from nltk.stem import WordNetLemmatizer

In [8]:
lemmatizer = WordNetLemmatizer()

In [9]:
import nltk,re
nltk.download('stopwords')
from nltk.corpus import stopwords
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


True

In [10]:
corpus=[]
for i in range(0,len(messages)):
    review=re.sub('[^a-zA-z]',' ',messages['message'][i]) #substituiting, apart from a-z and A-Z, if you get any special character then just replace it with the blank and try to replace it in our message and store it in our review variable
    review=review.lower()
    review=review.split()
    review=[lemmatizer.lemmatize(word) for word in review]
    review=' '.join(review)
    corpus.append(review)


In [64]:
[[i,j,k] for i,j,k in zip(list(map(len,corpus)),corpus, messages['message']) if i<1]

[[0, '', '645'], [0, '', ':) '], [0, '', ':-) :-)']]

In [11]:
corpus

['go until jurong point crazy available only in bugis n great world la e buffet cine there got amore wat',
 'ok lar joking wif u oni',
 'free entry in a wkly comp to win fa cup final tkts st may text fa to to receive entry question std txt rate t c s apply over s',
 'u dun say so early hor u c already then say',
 'nah i don t think he go to usf he life around here though',
 'freemsg hey there darling it s been week s now and no word back i d like some fun you up for it still tb ok xxx std chgs to send to rcv',
 'even my brother is not like to speak with me they treat me like aid patent',
 'a per your request melle melle oru minnaminunginte nurungu vettam ha been set a your callertune for all caller press to copy your friend callertune',
 'winner a a valued network customer you have been selected to receivea prize reward to claim call claim code kl valid hour only',
 'had your mobile month or more u r entitled to update to the latest colour mobile with camera for free call the mobile up

In [12]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [13]:
simple_preprocess

<function gensim.utils.simple_preprocess(doc, deacc=False, min_len=2, max_len=15)>

In [14]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [85]:
words = [simple_preprocess(sent) for sent in corpus]

In [86]:
words

[['go',
  'until',
  'jurong',
  'point',
  'crazy',
  'available',
  'only',
  'in',
  'bugis',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'there',
  'got',
  'amore',
  'wat'],
 ['ok', 'lar', 'joking', 'wif', 'oni'],
 ['free',
  'entry',
  'in',
  'wkly',
  'comp',
  'to',
  'win',
  'fa',
  'cup',
  'final',
  'tkts',
  'st',
  'may',
  'text',
  'fa',
  'to',
  'to',
  'receive',
  'entry',
  'question',
  'std',
  'txt',
  'rate',
  'apply',
  'over'],
 ['dun', 'say', 'so', 'early', 'hor', 'already', 'then', 'say'],
 ['nah',
  'don',
  'think',
  'he',
  'go',
  'to',
  'usf',
  'he',
  'life',
  'around',
  'here',
  'though'],
 ['freemsg',
  'hey',
  'there',
  'darling',
  'it',
  'been',
  'week',
  'now',
  'and',
  'no',
  'word',
  'back',
  'like',
  'some',
  'fun',
  'you',
  'up',
  'for',
  'it',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chgs',
  'to',
  'send',
  'to',
  'rcv'],
 ['even',
  'my',
  'brother',
  'is',
  'not',
  'like',
  'to',
  'spea

In [88]:
len(words)

5572

In [17]:
import gensim

In [18]:
# lets train Word2Vec from scratch
model=gensim.models.Word2Vec(words)

to get all the vocabulary

In [19]:
model.wv.index_to_key

['you',
 'to',
 'the',
 'and',
 'it',
 'in',
 'is',
 'me',
 'my',
 'for',
 'your',
 'call',
 'of',
 'that',
 'have',
 'on',
 'now',
 'are',
 'can',
 'so',
 'but',
 'not',
 'or',
 'we',
 'do',
 'get',
 'at',
 'be',
 'if',
 'ur',
 'will',
 'with',
 'no',
 'just',
 'this',
 'gt',
 'lt',
 'how',
 'go',
 'up',
 'when',
 'ok',
 'day',
 'what',
 'free',
 'from',
 'out',
 'all',
 'know',
 'll',
 'come',
 'like',
 'time',
 'good',
 'am',
 'then',
 'got',
 'wa',
 'there',
 'he',
 'text',
 'only',
 'love',
 'want',
 'send',
 'one',
 'need',
 'txt',
 'today',
 'by',
 'going',
 'home',
 'don',
 'stop',
 'she',
 'about',
 'lor',
 'sorry',
 'see',
 'mobile',
 'still',
 'take',
 'back',
 'da',
 'reply',
 'our',
 'think',
 'tell',
 'dont',
 'week',
 'phone',
 'hi',
 'new',
 'later',
 'they',
 'any',
 'pls',
 'her',
 'please',
 'ha',
 'co',
 'msg',
 'did',
 'been',
 'min',
 'an',
 'some',
 'dear',
 'make',
 'here',
 'night',
 'who',
 'message',
 'well',
 'say',
 'where',
 're',
 'thing',
 'much',
 'clai

In [20]:
model.corpus_count

5569

In [21]:
model.epochs

5

In [22]:
model.wv.similar_by_word('good')

[('wa', 0.998846709728241),
 ('amp', 0.9988033771514893),
 ('happy', 0.9987797141075134),
 ('day', 0.9987338781356812),
 ('morning', 0.9987232089042664),
 ('oh', 0.9985955357551575),
 ('well', 0.9985851049423218),
 ('where', 0.9985641241073608),
 ('night', 0.9985302686691284),
 ('all', 0.9985178112983704)]

In [23]:
model.wv['good']

array([-0.27238473,  0.3253122 ,  0.2701581 ,  0.17566545,  0.17752302,
       -0.6001676 ,  0.44363487,  0.81988555, -0.44675875, -0.22762574,
       -0.21973158, -0.5992981 , -0.10124626,  0.1046488 ,  0.11668093,
       -0.20673351,  0.0625063 , -0.4167892 ,  0.03010521, -0.691684  ,
        0.24590199,  0.41473702,  0.13587312, -0.32513037, -0.02711009,
        0.07265441, -0.36236337, -0.33344793, -0.35007775, -0.01698165,
        0.31894916,  0.05552861,  0.3050851 , -0.19861786, -0.0827902 ,
        0.46531597, -0.01715973, -0.2822515 , -0.16504487, -0.65417033,
        0.14017569, -0.32007265, -0.3164542 , -0.07141656,  0.34514448,
       -0.14458713, -0.21385588, -0.09610169,  0.22312863,  0.20922738,
        0.19860345, -0.2951669 , -0.14328536,  0.07111384, -0.19505471,
        0.1475344 ,  0.10805003,  0.03379747, -0.5315705 ,  0.20404334,
       -0.15012003,  0.14068843,  0.05253165, -0.2078579 , -0.51924413,
        0.43581194,  0.18484014,  0.3249933 , -0.51026314,  0.36

In [24]:
model.wv['good'].shape

(100,)

In [25]:
words[0]

['go',
 'until',
 'jurong',
 'point',
 'crazy',
 'available',
 'only',
 'in',
 'bugis',
 'great',
 'world',
 'la',
 'buffet',
 'cine',
 'there',
 'got',
 'amore',
 'wat']

In [89]:
def avg_word2vec(doc):
    # remove out-of-vocabulary words
    #sent = [word for word in doc if word in model.wv.index_to_key]
    #print(sent)

    vectors = [model.wv[word] for word in doc if word in model.wv.index_to_key]

    if len(vectors) == 0:
        return np.zeros(model.vector_size)

    return np.mean(vectors, axis=0)

                #or [np.zeros(len(model.wv.index_to_key))], axis=0)

In [43]:
! pip install tqdm

In [44]:
from tqdm import tqdm
import numpy as np

In [90]:
X=[]
for i in tqdm(range(len(words))):
    X.append(avg_word2vec(words[i]))

100%|██████████| 5572/5572 [00:00<00:00, 6324.57it/s]


In [91]:
X

[array([-0.17861906,  0.23275203,  0.18329702,  0.13511619,  0.11447611,
        -0.40391663,  0.28647092,  0.5739509 , -0.3363211 , -0.13826193,
        -0.17568856, -0.40223512, -0.06122736,  0.06528157,  0.0757946 ,
        -0.14458998,  0.05284007, -0.29949766,  0.02702954, -0.48194328,
         0.17777334,  0.29087782,  0.10290591, -0.2172441 , -0.03261144,
         0.06992256, -0.25864843, -0.21647577, -0.23922941,  0.02750121,
         0.21996413,  0.03271434,  0.19449653, -0.14858523, -0.03696732,
         0.34052855, -0.02078969, -0.19302759, -0.12356105, -0.4697148 ,
         0.0915678 , -0.23557718, -0.22968067, -0.04276039,  0.23246856,
        -0.09281499, -0.15645272, -0.06827651,  0.15469578,  0.1331223 ,
         0.13378377, -0.23402731, -0.0999563 ,  0.04891298, -0.14514908,
         0.09931953,  0.07866634,  0.01937588, -0.38512647,  0.14737336,
        -0.1180682 ,  0.08838709,  0.05455734, -0.13176891, -0.36583045,
         0.3215185 ,  0.1395573 ,  0.22983792, -0.3

In [92]:
len(X)

5572

# Independent Features

In [93]:
X_new=np.array(X)

In [94]:
messages.shape

(5572, 2)

3 data points are missing, fixing this is y i.e. making y's shape similar

In [95]:
X_new.shape

(5572, 100)

In [96]:
X_new[0].shape

(100,)

# Dependent Features

In [97]:
y=messages[list[map(lambda x: len(x)>0, words)]]
y=pd.get_dummies(y['label'])
y=y.iloc[:,0].values

In [98]:
y.shape

(5572,)

In [99]:
len(messages)

5572

In [100]:
len(words)

5572

This is the final Independent Features

In [107]:
df = pd.DataFrame(X)

In [108]:
df.shape

(5572, 100)

In [106]:
X[0].reshape(1,-1).shape

(1, 100)

In [109]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,-0.178619,0.232752,0.183297,0.135116,0.114476,-0.403917,0.286471,0.573951,-0.336321,-0.138262,...,0.347714,0.184286,0.086544,0.161970,0.431708,0.208406,0.069772,-0.211794,0.119325,-0.045899
1,-0.163253,0.202358,0.159665,0.109776,0.106577,-0.349789,0.239772,0.494410,-0.289250,-0.114725,...,0.302063,0.151544,0.068173,0.137747,0.366289,0.182790,0.056043,-0.193730,0.099408,-0.034856
2,-0.180301,0.241761,0.200133,0.157139,0.122038,-0.432639,0.271999,0.582953,-0.373483,-0.128737,...,0.373397,0.189762,0.083513,0.167570,0.427905,0.200880,0.057874,-0.227213,0.136569,-0.026290
3,-0.245190,0.319483,0.245969,0.180461,0.157106,-0.545470,0.390713,0.773067,-0.455670,-0.188873,...,0.461012,0.237048,0.105240,0.222873,0.576619,0.285955,0.095132,-0.299587,0.151384,-0.050481
4,-0.211403,0.260455,0.214445,0.149712,0.142981,-0.460382,0.324329,0.650087,-0.381270,-0.165675,...,0.396010,0.200376,0.096308,0.193019,0.486613,0.247879,0.074419,-0.250466,0.130182,-0.045542


Independent Feature

In [110]:
X=df

Train Test Split

In [111]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20)

In [112]:
X_train.head()

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
2799,-0.114222,0.257366,0.172520,0.122979,0.067114,-0.396897,0.335709,0.561607,-0.332850,-0.139850,...,0.323908,0.215060,0.142053,0.165137,0.464618,0.219211,0.136078,-0.128166,0.101550,-0.116748
1998,-0.248704,0.293810,0.248603,0.165846,0.171269,-0.537288,0.367257,0.742938,-0.427730,-0.192925,...,0.446895,0.223874,0.102545,0.215324,0.557803,0.280286,0.078995,-0.292832,0.159360,-0.035911
3674,-0.234703,0.301790,0.240607,0.162944,0.145815,-0.527928,0.372739,0.750613,-0.431161,-0.183585,...,0.454235,0.243952,0.118731,0.212283,0.565316,0.283347,0.095437,-0.271046,0.151839,-0.060223
892,-0.294764,0.290622,0.284720,0.144229,0.203602,-0.593103,0.399369,0.815760,-0.420850,-0.256258,...,0.479855,0.199636,0.086989,0.250352,0.610394,0.341953,0.041740,-0.365344,0.160448,0.014159
1231,-0.222419,0.296884,0.230686,0.155981,0.149154,-0.512661,0.367971,0.725609,-0.414826,-0.186820,...,0.440794,0.229597,0.109718,0.202781,0.548022,0.268600,0.091926,-0.265032,0.140307,-0.053413


In [114]:
y_train

array([ True,  True,  True, ...,  True,  True,  True])

In [116]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()

In [117]:
rf.fit(X_train,y_train)

RandomForestClassifier()

In [119]:
y_pred=rf.predict(X_test)

In [120]:
y_pred

array([ True,  True,  True, ...,  True, False,  True])

In [121]:
from sklearn.metrics import accuracy_score,classification_report
print(accuracy_score(y_test,y_pred))

0.967713004484305


In [122]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

       False       0.91      0.84      0.88       150
        True       0.98      0.99      0.98       965

    accuracy                           0.97      1115
   macro avg       0.94      0.91      0.93      1115
weighted avg       0.97      0.97      0.97      1115

